services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: assistant_financier
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data


  backend:
    build: ../backend
    ports:
      - "8081:8081"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/assistant_financier
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: password
      HUGGING_FACE_API_KEY: ${HUGGING_FACE_API_KEY:-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}

  frontend:
    build: ../frontend
    ports:
      - "80:80"
    depends_on:
      - backend

  frontend-web:
    image: nginx:alpine
    volumes:
      - ../frontend-web:/usr/share/nginx/html
      - ../frontend-web/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  postgres_data: